
// Todo app
export const GET_TODO_LOADING = 'GET_TODO_LOADING'
export const GET_TODO_SUCCESS = 'GET_TODO_SUCCESS'
export const GET_TODO_FAILURE = 'GET_TODO_FAILURE'


export const ADD_TODO_LOADING = 'ADD_TODO_LOADING'
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS'
export const ADD_TODO_FAILURE = 'ADD_TODO_FAILURE'

export const DELETE_TODO_LOADING = 'DELETE_TODO_LOADING';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_TODO_ERROR = 'DELETE_TODO_ERROR';

export const TOGGLE_TODO_LOADING = 'TOGGLE_TODO_LOADING';
export const TOGGLE_TODO_SUCCESS = 'TOGGLE_TODO_SUCCESS';
export const TOGGLE_TODO_ERROR = 'TOGGLE_TODO_ERROR';

export const EDIT_TODO_LOADING = 'EDIT_TODO_LOADING';
export const EDIT_TODO_SUCCESS = 'EDIT_TODO_SUCCESS';
export const EDIT_TODO_ERROR = 'EDIT_TODO_ERROR';




